version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

volumes:
  db:
  nextcloud:





user: nextcloud
pass: my-secret-pw
